<a href="https://colab.research.google.com/github/NeoByteVoyager/PytorchLearning/blob/main/ML/Pytorch_in_1_hour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 一.Tensor


## Create tensor

### 1.Direct change from data

In [ ]:
import torch
data = [[1,2,3],[4,5,6]]
my_tensor=torch.tensor(data)
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


### 2.Creation from a desired shape

In [ ]:
shape=(2,3)

ones=torch.ones(shape)
zeros=torch.zeros(shape)
random=torch.randn(shape)

print(f"Random tensor:\n{random}")

Random tensor:
tensor([[ 0.3021, -0.6535, -1.4957],
        [ 0.2992,  0.6160,  0.5320]])


### 3.Creation by mimicking another tensor

In [ ]:
template=torch.tensor([[1,2],[3,4]])
# creation a new tensor with the same properties
rand_like=torch.rand_like(template,dtype=torch.float)
print(f"Template tensor:\n{template}")
print(f"Rand_like tensor:\n{rand_like}")



Template tensor:
tensor([[1, 2],
        [3, 4]])
Rand_like tensor:
tensor([[0.9437, 0.1720],
        [0.9267, 0.3156]])


## The 3 critical attributes of tensor

In [ ]:
import torch
tensor=torch.randn(2,3)

print(f"Shape:{tensor.shape}")
print(f"Datatype:{tensor.dtype}")
print(f"Device:{tensor.device}")

Shape:torch.Size([2, 3])
Datatype:torch.float32
Device:cpu


# 二.Autograd

## Switch


**switch:**`requires_grad=True`  
It send a message to the autograd engine "This is a parameter.From now on,**track every single operation** that happens to it."

## Data vs Parameter

In [ ]:
import torch
x_data = torch.tensor([[1.,2.],[3.,4.]])
w = torch.tensor([[1.],[2.]],requires_grad=True)
print(f"Data tensor requires_grad:{x_data.requires_grad}")
print(f"Parameter tensor requires_grad:{w.requires_grad}")

Data tensor requires_grad:False
Parameter tensor requires_grad:True


## Computation Graph & .grad_fn

In [ ]:
a=torch.tensor(2.0,requires_grad=True)
b=torch.tensor(3.0,requires_grad=True)
c=torch.tensor(4.0,requires_grad=True)

y=a*b

z=y+c

print(z)
print(f"grad_fn for z:{z.grad_fn}")
print(f"grad_fn for y:{y.grad_fn}")
print(f"grad_fn for a:{a.grad_fn}")

tensor(10., grad_fn=<AddBackward0>)
grad_fn for z:<AddBackward0 object at 0x7a56f8c8c970>
grad_fn for y:<MulBackward0 object at 0x7a56f8c8c970>
grad_fn for a:None


# 三.Reduction operations & The dim argument

## Mean


In [ ]:
# Base
x=torch.tensor([1.,2.,3.,4.])
res=x.mean()
print(res)
# Dim Average
x = torch.tensor([[1.0, 2.0, 3.0],
          [4.0, 5.0, 6.0]])
# dim = 0
print(x.mean(dim=0))
# dim = 1
print(x.mean(dim=1).shape)
print(x.mean(dim=1,keepdim=True).shape) # 保持维度，使其还是矩阵，而不是退化为向量



tensor(2.5000)
tensor([2.5000, 3.5000, 4.5000])
torch.Size([2])
torch.Size([2, 1])


# 四.Selecting Data




## Basic indexing

In [ ]:
x=torch.arange(12).reshape(3,4)
print(x)
# Get the third column (index=2)
col_2=x[:,2]
print(col_2)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 2,  6, 10])


## Dynamic selection


### 1.argmax

In [ ]:
x = torch.tensor([1.2, 5.5, 3.1, 0.8])
idx=x.argmax()
print(idx)
x = torch.tensor([[1.0, 6.0, 3.0],
          [4.0, 2.0, 5.0]])
print(x.argmax(dim=0))
print(x.argmax(dim=1))

# Practice:possibility to class
# 行代表：第几张图片； 列代表：它是[猫, 狗, 鸟]的概率分数
outputs = torch.tensor([[0.1, 0.8, 0.1],   # 预测第1张图
              [0.7, 0.2, 0.1],   # 预测第2张图
              [0.3, 0.3, 0.4]])  # 预测第3张图

# 真实标签（Ground Truth）
labels = torch.tensor([1, 0, 2]) # 分别是：狗、猫、鸟
# prediction
preds=outputs.argmax(dim=1)
print(preds)
acc= (preds==labels).float().mean()
print(f"accuracy:{acc}")

### 2.gather

In [ ]:
import torch

#  input
scores = torch.tensor([[70, 80, 90],   # 学生 0 的 [语文, 数学, 英语]
             [60, 95, 85],   # 学生 1 的 [语文, 数学, 英语]
             [75, 88, 92]])  # 学生 2 的 [语文, 数学, 英语]
index_dim1=torch.tensor([[0,0,2],
            [1,2,0],
            [0,0,1]])
res=torch.gather(scores,1,index_dim1)
print(res)
index_dim0=torch.tensor([[0,0,2],
            [1,2,0],
            [0,0,1]])
res=scores.gather(0,index_dim0)
print(res)
index_dim1=torch.tensor([[1],
            [0],
            [2]])
print(scores.gather(1,index_dim1))

tensor([[70, 70, 90],
        [95, 85, 60],
        [75, 75, 88]])
tensor([[70, 80, 92],
        [60, 88, 90],
        [70, 80, 85]])
tensor([[80],
        [60],
        [92]])


# 五.Build a simple model

In [ ]:
import torch
# 训练数据
X=torch.tensor([[1.2240], [-1.8022], [-1.3247], [-0.2105], [-0.3388]])
Y=torch.tensor([[3.4480], [-2.6044], [-1.6495],  [0.5790],  [0.3225]])
# 参数
W=torch.randn(1,1,requires_grad=True)
b=torch.randn(1,requires_grad=True)


# 设置超参数
alpha,epoches=0.01,1000

for epoch in range(epoches):
  Y_hat=X@W+b
  # 前向传播
  loss=((Y-Y_hat)**2).mean()

  # 反向传播
  loss.backward()
  with torch.no_grad():
    W-=alpha*W.grad
    b-=alpha*b.grad
    if epoch%10==0:
      print(f"epoch:{epoch:4d} ： loss:{loss.item():.4f} | W:{W.item():.4f} | b:{b.item():.4f}")
    W.grad.zero_()
    b.grad.zero_()


## 六.Torch.nn

- `torch.nn.Module`是一个基类("模板"),是**一个框架**,可以规定如何初始化`__init__`(网络的形状)以及`forward`(网络是如何流动的)
- `torch.nn.Linear`(全连接层)只是一个零件,自动创建`parameter`，并初始化

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
# 训练数据
X=torch.tensor([[1.2240], [-1.8022], [-1.3247], [-0.2105], [-0.3388]])
Y=torch.tensor([[3.4480], [-2.6044], [-1.6495],  [0.5790],  [0.3225]])
# 创建自己的模型
class MyModel(nn.Module):
  def __init__(self,in_features,out_features):
    super().__init__()
    self.linear=nn.Linear(in_features,out_features)
  def forward(self,x):
    return self.linear(x)
# 实例化模型
model=MyModel(1,1)
# 第一损失函数和优化器
criterion=nn.MSELoss()  # 定义损失函数，代替手写((Y-Y_hat)**2).mean()
optimizer=optim.SGD(model.parameters(),lr=0.01) # 参数交给优化器管理,并设置学习率
for epoch in range(1000):
  # 前向传播
  Y_hat=model(X)
  # 计算损失函数
  loss=criterion(Y_hat,Y)

  # 清空梯度
  optimizer.zero_grad()
  # 反向传播
  loss.backward()
  # 更新参数
  optimizer.step()
'''
  if epoch%10==0:
    print(f"epoch:{epoch:4d}|loss:{loss.item():4f}|weights:{model.linear.weight.item():.4f}|bias:{model.linear.bias.item():.4f}")
'''
print(model)

MyModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)
